<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_previous</name>
   <tag></tag>
   <elementGuidId>ed6e400f-0de8-4b46-b30a-654ca320bbe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm pull-left uib-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>move(-1)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>previous</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-763-1239-panel&quot;)/div[@class=&quot;panel-body&quot;]/iad-my-iad-accordion-group-body[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-accordion-group-body&quot;]/ng-transclude[1]/div[@class=&quot;ng-scope&quot;]/iad-headquarter-bi-partner-step-agreements[@class=&quot;ng-scope ng-isolate-scope&quot;]/iad-block[@class=&quot;ng-isolate-scope&quot;]/section[@class=&quot;iad-block margin-top-20&quot;]/div[@class=&quot;iad-block-content clearfix&quot;]/iad-block-body[@class=&quot;ng-scope&quot;]/iad-bi-convention[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-xs-6&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;ng-pristine ng-untouched ng-valid ng-scope ng-empty ng-valid-date-disabled&quot;]/ul[@class=&quot;uib-datepicker-popup dropdown-menu ng-scope&quot;]/li[1]/div[@class=&quot;ng-scope ng-isolate-scope uib-datepicker&quot;]/div[1]/div[@class=&quot;uib-daypicker ng-scope&quot;]/table[1]/thead[1]/tr[1]/th[1]/button[@class=&quot;btn btn-default btn-sm pull-left uib-left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-763-1239-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-headquarter-bi-partner-step-agreements/iad-block/section/div/iad-block-body/iad-bi-convention/div[2]/div/div/div/ul/li/div/div/div/table/thead/tr/th/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date de signature'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner un type de convention ...'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mars 2020'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
   </webElementXpaths>
</WebElementEntity>
