<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Taux chelonn_checkround</name>
   <tag></tag>
   <elementGuidId>cfc09618-524a-4619-9bb2-512d7dc9afcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiongroup-764-7511-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-headquarter-bi-partner-step-agreements/iad-block[2]/section/div/iad-block-body/iad-bi-agreement-with-iad/div/div/div/label[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkround</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-764-7511-panel&quot;)/div[@class=&quot;panel-body&quot;]/iad-my-iad-accordion-group-body[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;myiad-accordion-group-body&quot;]/ng-transclude[1]/div[@class=&quot;ng-scope&quot;]/iad-headquarter-bi-partner-step-agreements[@class=&quot;ng-scope ng-isolate-scope&quot;]/iad-block[@class=&quot;ng-isolate-scope&quot;]/section[@class=&quot;iad-block margin-top-20&quot;]/div[@class=&quot;iad-block-content clearfix&quot;]/iad-block-body[@class=&quot;ng-scope&quot;]/iad-bi-agreement-with-iad[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;row form-group ng-valid ng-dirty ng-valid-parse&quot;]/div[@class=&quot;col-xs-6&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;iad-label bi-radio-input&quot;]/span[@class=&quot;checkround&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-764-7511-panel']/div/iad-my-iad-accordion-group-body/div/ng-transclude/div/iad-headquarter-bi-partner-step-agreements/iad-block[2]/section/div/iad-block-body/iad-bi-agreement-with-iad/div/div/div/label[2]/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
